export const BASE_PLAYER_HEALTH = 100
export const LEGACY_PLAYER_DAMAGE_SCALE = 34
export const HULL_UPGRADE_AMOUNT = 15
export const RUN_HULL_REINFORCEMENT_AMOUNT = 15
export const GLASS_REACTOR_HEALTH = 25
export const HEALTH_ORB_RECOVERY = 20
export const REPAIR_PULSE_RECOVERY = 25
export const MEDIC_DRONE_RECOVERY = 10
