export const tags = {
	friendly: "friendly",
	enemy: "enemy",
	props: "props",
	gameLoopUi: "game_loop_ui",
	gameLoop: "gameLoop",
	mainMenu: "mainMenu",
	pauseMenu: "pauseMenu",
	deathScreen: "deathScreen",
	levelTransition: "levelTransition",
	commandConsole: "commandConsole",
	recoveryShop: "recoveryShop",
	hubFacilityUi: "hubFacilityUi",
	trainingTarget: "trainingTarget",
	runMap: "runMap",
	damageNumber: "damageNumber",
	tacticalMap: "tacticalMap",
	hubBoundary: "hubBoundary",
	hubPhaseField: "hubPhaseField",

	blaster: "blaster",
	rocket: "rocket",
	projectile: "projectile",
	stressProjectile: "stressProjectile",
	debree: "debree",
	unit: "unit",
	elite: "elite",
	threatEnemy: "threatEnemy",
	part: "part",
	follower: "follower",
	player: "player",
	hackedAlly: "hackedAlly",

	levelBg: "level_bg",

	levelEditor: "levelEditor",
	layerToggle: "layerToggle",
	brightnessSlider: "brightnessSlider",
};
